[build]
builder = "NIXPACKS"
buildCommand = "./mvnw -DskipTests clean package"

[deploy]
startCommand = "java -Dserver.port=$PORT -jar target/ims-0.0.1-SNAPSHOT.jar"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
